project_id = "ocsptehtkawcpcgckqeh"

[functions]
  [functions.ai-agent]
    verify_jwt = true
  [functions.ai-chat]
    verify_jwt = true
  [functions.ai-core]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.equipos-api]
    verify_jwt = false
  [functions.groq-chat]
    verify_jwt = true
  [functions.mcp-server]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-pin-email]
    verify_jwt = true
