
-- ============================================
-- Migración: Sistema de Overrides de Planes
-- Permite asignar planes manualmente a equipos
-- ============================================

-- 1. Crear tabla overrides_planes
CREATE TABLE IF NOT EXISTS public.overrides_planes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ficha_equipo TEXT NOT NULL,
  plan_original_id BIGINT REFERENCES public.planes_mantenimiento(id),
  plan_forzado_id BIGINT NOT NULL REFERENCES public.planes_mantenimiento(id),
  motivo TEXT NOT NULL DEFAULT '',
  usuario_email TEXT NOT NULL DEFAULT 'sistema@local',
  activo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. Índices para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_overrides_planes_ficha ON public.overrides_planes(ficha_equipo);
CREATE INDEX IF NOT EXISTS idx_overrides_planes_activo ON public.overrides_planes(activo);
CREATE INDEX IF NOT EXISTS idx_overrides_planes_plan_forzado ON public.overrides_planes(plan_forzado_id);

-- 3. Trigger para updated_at automático
CREATE OR REPLACE FUNCTION public.update_overrides_planes_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

DROP TRIGGER IF EXISTS trigger_update_overrides_planes_updated_at ON public.overrides_planes;
CREATE TRIGGER trigger_update_overrides_planes_updated_at
  BEFORE UPDATE ON public.overrides_planes
  FOR EACH ROW
  EXECUTE FUNCTION public.update_overrides_planes_updated_at();

-- 4. Habilitar RLS
ALTER TABLE public.overrides_planes ENABLE ROW LEVEL SECURITY;

-- 5. Políticas RLS (acceso público para esta aplicación)
CREATE POLICY "Permitir lectura pública de overrides_planes" 
  ON public.overrides_planes FOR SELECT 
  USING (true);

CREATE POLICY "Permitir inserción pública de overrides_planes" 
  ON public.overrides_planes FOR INSERT 
  WITH CHECK (true);

CREATE POLICY "Permitir actualización pública de overrides_planes" 
  ON public.overrides_planes FOR UPDATE 
  USING (true);

CREATE POLICY "Permitir eliminación pública de overrides_planes" 
  ON public.overrides_planes FOR DELETE 
  USING (true);

-- 6. Crear vista equipos_con_overrides para consultas rápidas
CREATE OR REPLACE VIEW public.equipos_con_overrides AS
SELECT 
  o.ficha_equipo,
  o.plan_original_id,
  o.plan_forzado_id,
  o.motivo,
  o.usuario_email,
  o.created_at AS override_fecha,
  pm_original.nombre AS plan_original_nombre,
  pm_forzado.nombre AS plan_forzado_nombre,
  pm_forzado.marca AS plan_marca,
  pm_forzado.modelo AS plan_modelo
FROM public.overrides_planes o
LEFT JOIN public.planes_mantenimiento pm_original ON o.plan_original_id = pm_original.id
JOIN public.planes_mantenimiento pm_forzado ON o.plan_forzado_id = pm_forzado.id
WHERE o.activo = true;

-- 7. Habilitar realtime para sincronización
ALTER PUBLICATION supabase_realtime ADD TABLE public.overrides_planes;

-- 8. Comentarios de documentación
COMMENT ON TABLE public.overrides_planes IS 'Overrides manuales de planes de mantenimiento para equipos específicos';
COMMENT ON VIEW public.equipos_con_overrides IS 'Vista de equipos con override activo y datos del plan forzado';
