// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const MISSING_CONFIG_MESSAGE =
  'Supabase no está configurado. Configura VITE_SUPABASE_URL y VITE_SUPABASE_PUBLISHABLE_KEY para habilitar la conexión.';

const createMissingConfigError = () => new Error(MISSING_CONFIG_MESSAGE);

const createQueryBuilderStub = () => {
  const getPromise = () => Promise.resolve({ data: null, error: createMissingConfigError() });

  const proxy: any = new Proxy(
    {},
    {
      get(_target, prop) {
        if (prop === 'then' || prop === 'catch' || prop === 'finally') {
          const promise = getPromise();
          return (promise as any)[prop].bind(promise);
        }
        return (..._args: any[]) => proxy;
      },
    },
  );

  return proxy;
};

const createChannelStub = () => {
  const channel: any = {
    on: () => channel,
    subscribe: () => ({ unsubscribe: () => {} }),
  };

  return channel;
};

const createDemoSupabaseClient = (): SupabaseClient<Database> => {
  if (typeof window !== 'undefined') {
    console.warn(MISSING_CONFIG_MESSAGE);
  }

  const authStub = {
    async getSession() {
      return { data: { session: null }, error: createMissingConfigError() };
    },
    async signInWithPassword() {
      return {
        data: { session: null, user: null },
        error: createMissingConfigError(),
      };
    },
    async signUp() {
      return {
        data: { session: null, user: null },
        error: createMissingConfigError(),
      };
    },
    async signOut() {
      return { error: createMissingConfigError() };
    },
    onAuthStateChange() {
      const subscription = { unsubscribe: () => {} };
      return {
        data: { subscription },
        error: createMissingConfigError(),
      };
    },
  };

  const client = {
    from: () => createQueryBuilderStub(),
    channel: () => createChannelStub(),
    removeChannel: () => {},
    auth: authStub,
    functions: {
      async invoke() {
        return { data: null, error: createMissingConfigError() };
      },
    },
    async rpc() {
      return { data: null, error: createMissingConfigError() };
    },
  } as unknown as SupabaseClient<Database>;

  return client;
};

export const isSupabaseConfigured = Boolean(
  SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY,
);

// Importa el cliente de Supabase de la siguiente forma:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createDemoSupabaseClient();